import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { MainPrivider } from "./_mainPrivider";

const DMSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Peony",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${DMSans.variable} antialiased bg-[var(--white)]`}>
        <MainPrivider>{children}</MainPrivider>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
